### ISSUE TITLE
Dependencies Install in Linux Anaconda

### ISSUE THREAD

**Issue by HOBIHer** [WarmongeringBeaver/diffusion-comparison-experiments#6]
In Dependencies Section
To install the required dependencies, run:
`{conda, mamba} install -f environment.yaml`

It leads to Error as follows:
```
$ conda install -f environment.yaml

PackagesNotFoundError: The following packages are not available from current channels:

environment.yaml

Current channels:
defaults
```

It works when I use command
`conda env update -f environment.yaml`
(Or` conda env create -f environment.yaml `for a new conda env)

**Comment by thethomasboyer** [comment]
Thanks, I wrote the syntax for mamba but it's actually incorrect for conda :)
